### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by RyanSMurphyDMCo** [getyoti/yoti-node-sdk#26]
Hi. 

I am a developer at a new client of Yoti. 

We are working on the Yoti integration, in our Serverless/NodeJS/TypeScript application and its not proving straightforward.

I am trying to retrieve a profile. My code is based on the developer documentation and the examples in this repository. When I run my code I get the error:

`TypeError: Cannot read property 'toString' of undefined
    at encodeBuffer (/Users/ryan.murphy/GitHub/sls_verification_age/node_modules/ursa/lib/ursa.js:183:16)
    at identifyPemType (/Users/ryan.murphy/GitHub/sls_verification_age/node_modules/ursa/lib/ursa.js:70:15)
    at isPrivateKeyPem (/Users/ryan.murphy/GitHub/sls_verification_age/node_modules/ursa/lib/ursa.js:94:16)
    at Object.createPrivateKey (/Users/ryan.murphy/GitHub/sls_verification_age/node_modules/ursa/lib/ursa.js:445:14)
    at decryptToken (/Users/ryan.murphy/GitHub/sls_verification_age/node_modules/yoti/src/client/index.js:8:27)
    at YotiClient.getActivityDetails (/Users/ryan.murphy/GitHub/sls_verification_age/node_modules/yoti/src/client/index.js:27:24)
    at YotiHelper.retrieveProfile (/Users/ryan.murphy/GitHub/sls_verification_age/src/common/YotiHelper.ts:12:25)
    at Object.<anonymous> (/Users/ryan.murphy/GitHub/sls_verification_age/src/controllers/health.ts:15:14)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ryan.murphy/GitHub/sls_verification_age/.build/src/controllers/health.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)`

And this is my code (please ignore code quality, its just for testing integration atm: 

```
export class YotiHelper {

    private yoti = require('yoti');
    private yotiClient: any;
    
    constructor () {
        const CLIENT_SDK_ID = 'secret key here';
        this.yotiClient = new this.yoti.Client(CLIENT_SDK_ID, process.env.YOTI_PEM_KEY);
    }

    public retrieveProfile() {
        const promise = this.yotiClient.getActivityDetails('rZ8o2WJWv-5B70dPKny3PEWNkZZOm0g504uOcBphpgsZGiqBmszaoL6czzDB018zURVrrK6ZGsXLm3iLN3AiwLGk5HufA9yVCRyAb3iXcLBZwHmMziyo5nZ_0Ko4022DqMhxs6kp19J6ZME7vHnzT_Hx2x4vUzvRgGK_PC2AO7dPovxjwvWHq_1lE4tsqS82HqKfypGKQ9TGrS6aJkCFE6ZYPM7RVZZNoUoHa_KlXJQCJ8hDiCM9zz3xSWQoslSa81zuq2pygHXK9j9THQi85qYwQ_ajR1P7tuT5rTsVTnRiTqi_rv_p-z8qOkxtiH5eBHSgMPvVZOW653dGa5eLvg==');
        promise.then((activityDetails: any) => {
            
          }).catch((err: any) => {
            console.error(err);            
          });
    }
} ```

**Comment by sidibos** [comment]
This is due to hardcoded token. A token is valid for a period of time and can only be used once.
